### ISSUE TITLE
Can I use this in iOS?

### ISSUE THREAD

**Issue by EMakadiya** [ppwwyyxx/speaker-recognition#10]
Hi @ppwwyyxx 

Can I use this for mobile platform? I want to do same like this in iOS so I am searching but not get anything in iOS. I saw your demo video its working file. So I want to implement this in iOS. Can you guide me how can I do ? Or how can I run this on mac?

-Ekta

**Comment by ppwwyyxx** [comment]
It's python so probably cannot run in iOS app.
Mac should be fine as long as the dependencies can compile.

**Comment by EMakadiya** [comment]
@ppwwyyxx  okay. 

But do you know how can I achieve this in iOS?

**Comment by ppwwyyxx** [comment]
I think they need to be completely rewritten in C or swift, etc.

**Comment by EMakadiya** [comment]
Okay. Thanks for response. :)
