### ISSUE TITLE
have some errors

### ISSUE THREAD

**Issue by hongzhangMu** [ppwwyyxx/speaker-recognition#11]
hi:
I have gcc>=4.7 on mac osx10.11. when I make  gmm, this have some errors .can you help me?
[cc] src//kmeans.cc ...
clang: warning: -lm: 'linker' input unused
clang: warning: -lpthread: 'linker' input unused
src//kmeans.cc:165:19: error: use of undeclared identifier 'ceil'
        int block_size = ceil((double)n / concurrency);
                         ^
src//kmeans.cc:193:7: error: use of undeclared identifier 'fabs'
                if (fabs(last_distsqr_sum - distsqr_sum) < 1e-6) { // || fabs(dist...
                    ^
src//kmeans.cc:266:19: error: use of undeclared identifier 'ceil'
        int block_size = ceil((double)n / concurrency);
                         ^
src//kmeans.cc:298:7: error: use of undeclared identifier 'fabs'
                if (fabs(last_distsqr_sum - distsqr_sum) < 1e-6)// || fabs(distsqr...
                    ^
4 errors generated.
make: *** [obj/src//kmeans.o] Error 1

**Comment by ppwwyyxx** [comment]
You're not using gcc, otherwise you won't see clang.

**Comment by hongzhangMu** [comment]
@ppwwyyxx thanks. What's more, i still have some errors. when i build bob,bob.blitz has some errors.
you tell me Install blitz as Bob dependency. it means i can not instill bob.blitz? thanks

**Comment by ppwwyyxx** [comment]
It means you should first install blitz then bob.

**Comment by hongzhangMu** [comment]
hi:
i can't install bob . can you tell me which versions in operate system. ubuntu？or cent os？thanks

**Comment by ppwwyyxx** [comment]
It worked on ubuntu.

**Comment by hongzhangMu** [comment]
hi:
when I enrolled info, this has some errors.I can't understand this  errors.Thanks  @ppwwyyxx 
Enroll: 55.5080 seconds
Start training...
training from ubm ...
nr_instance   :   3468
nr_dim        :   28
nr_mixture    :   32
min_covar     :   0.001000
threshold     :   0.010000
nr_iteration  :   200
init_with_kmeans: 0
concurrency   :   1
verbosity     :   0
python: src/gmm.cc:177: real_t Gaussian::probability_of_fast_exp(std::vector<double>&, double*): Assertion `(int)x.size() == dim' failed.
Aborted (core dumped)

**Comment by ppwwyyxx** [comment]
There might be bugs in our gmm implementation but I didn't author that part.
You can simply not compile the gmm part, then a sklearn fallback will be used.

**Comment by jmrbcu** [comment]
Hi everyone, I was able to compile your **gmm** implementation on **OSX** adding **cmath** include to **src/gmm/src/kmeans.cc**:

#include <cassert>
#include <algorithm>
#include <functional>
#include <thread>
#include <mutex>
#include <queue>
#include <cmath>
**#include <cmath>**

I am using default clang from default OSX xcode:

Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin16.3.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Comment by ppwwyyxx** [comment]
OK. added cmath to kmeans.cc in latest commit.
