### ISSUE TITLE
高斯模型训练

### ISSUE THREAD

**Issue by tanghy2016** [ppwwyyxx/speaker-recognition#14]
您好，非常感谢分享，受益不少。
在我使用的过程中遇到一点问题，请问，如果注册时的数据量偏少的话，是不是学习到的高斯混合模型效果不会很好呢？如果想要模型学习得更好的话，能否有什么别的办法？因为不可能将一个人每个状况下说的话都记录下来进行训练嘛～

**Comment by cris7M** [comment]
$./speaker-recognition.py

Warning: failed to import fast-gmm, use gmm from scikit-learn instead
usage: speaker-recognition.py [-h] -t TASK -i INPUT -m MODEL
speaker-recognition.py: error: argument -t/--task is required

can u explain me and what is model.out file
