### ISSUE TITLE
SyntaxError:invalid syntax

### ISSUE THREAD

**Issue by William-zhang-t** [ppwwyyxx/speaker-recognition#15]
filters/utils.py，在这个文件里，只有如下这一行代码。
../gui/utils.py

在这里报错了，错误说是语法错误，这种写法好像确实不符合语法。不知道为什么在我这里会报错。恳请大神帮忙解答下，谢谢。

**Comment by ppwwyyxx** [comment]
Your filesystem doesn't support symbolic links. You're probably using windows.

**Comment by William-zhang-t** [comment]
非常激动你能回复，万分感谢。我用的是ubuntu。
1.配置环境时，首先，blitz提示安装成功了；然后安装bob时，提示pkg-config package 'blitz' was not found. 因此，感觉环境就没配置好。
2.还有，不太清楚，该如何执行。
最后再次感谢。

**Comment by ppwwyyxx** [comment]
You should install `libblitz-dev` from apt.
