### ISSUE TITLE
Open or closed set

### ISSUE THREAD

**Issue by jmrbcu** [ppwwyyxx/speaker-recognition#16]
What would happen if I have a trained model with 3 speakers, then, I try to identify a 4th speaker which is not in the trained model, what would be the answer in this case?

**Comment by ppwwyyxx** [comment]
It would be one of the 3.

**Comment by jmrbcu** [comment]
Is there any possibility to respond something like: I don't know who the 4th speaker is?

**Comment by ppwwyyxx** [comment]
We don't have this feature in this project.

**Comment by jmrbcu** [comment]
ok, is it possible to add it?

**Comment by ppwwyyxx** [comment]
You can certainly try it if you want.
