### ISSUE TITLE
Conversation mode from command line?

### ISSUE THREAD

**Issue by richardpenner** [ppwwyyxx/speaker-recognition#18]
I can train the model at the command line and have it predict successfully too. But I can't get the UI to work for whatever reason. I don't need the UI but I do want conversation mode. Can you outline how this might be done? I would be happy to help with a pull request but need some guidance. Thanks!

**Comment by ppwwyyxx** [comment]
The GUI is not under maintenance. But what it did is basically to record audio and run the recognition for every short piece of audio.

**Comment by richardpenner** [comment]
OK. So I could build something that records and predicts on say 1 second clips?

**Comment by sunnyclaracn** [comment]
In this case, does this package still has dependency on PyQt?

**Comment by sunnyclaracn** [comment]
If so, does this package still depends on PyQt4?

**Comment by sunnyclaracn** [comment]
If so, this package won't depend on PyQt4, right?

**Comment by sunnyclaracn** [comment]
Actually, when I try to install PyQt4, and make it, it reports error (in below), and haven't solved yet. Do you have any idea
===================
metatranslator.o: In function `MetaTranslator::messages() const':
metatranslator.cpp:(.text+0x236d): undefined reference to `__cxa_throw_bad_array_new_length'

**Comment by ppwwyyxx** [comment]
Yes it won't depend on pyqt.
I don't know why you would have problems installing it. You better report this to the pyqt project for advices.

**Comment by richardpenner** [comment]
@ppwwyyxx are you open to a pull request for putting conversation mode into the command-line interface?

**Comment by ppwwyyxx** [comment]
It would be good to have it, but I'm not sure I'll have the time to look at the code if it was very long.
I suppose it's not a very easy task. I remember we try different method of denoising, smoothing, etc (in gui.py and interface.py) to make it work well.

**Comment by richardpenner** [comment]
I haven't looked through the code very carefully, but I was going to start by refactoring  `do_conversation` and related code into something accessible from `speaker-recognition.py`. I would actually be happy to just use the interface, but I haven't figured out how it works, and you've mentioned that it's not supported.
