### ISSUE TITLE
Android Source

### ISSUE THREAD

**Issue by cris7M** [ppwwyyxx/speaker-recognition#19]
Hi, can I make the same application in android. and can u explain me their is some mathematics required to make this application.

Thanks in advance

**Comment by ppwwyyxx** [comment]
You can if you rewrite everything in C or Java.
It requires basic knowledge of machine learning and signal processing.

**Comment by cris7M** [comment]
Dear can i get the prototype means how should I start it and one more thing i am not from engineering background, even though can i create it. I need your help brother for not giving source code for giving guidelines..
Thank you vary much

**Comment by cris7M** [comment]
Please give me some guidance to make this application possible
Thanks

**Comment by ppwwyyxx** [comment]
1. understand the source code
2. rewrite them with java
3. build an android app to run the java code

**Comment by cris7M** [comment]
Thank you sir

**Comment by punit-kulal** [comment]
Permission:
Can we build an android app with your source code?

**Comment by ppwwyyxx** [comment]
You can use the code however you like as long as you follow the LICENSE.

But I don't think the source code will be helpful at all. As I said the code needs to be rewritten to run on android.

**Comment by cris7M** [comment]
Dear sir, am getting error here

$./speaker-recognition.py

Warning: failed to import fast-gmm, use gmm from scikit-learn instead
usage: speaker-recognition.py [-h] -t TASK -i INPUT -m MODEL
speaker-recognition.py: error: argument -t/--task is required

can u explain me and what is model.out file

**Comment by ppwwyyxx** [comment]
You are not following the [usage](https://github.com/ppwwyyxx/speaker-recognition#command-line-tools)

**Comment by cris7M** [comment]
fine sir, but i was asking about what is model.out file, shell put some wave file here.

**Comment by ppwwyyxx** [comment]
model.out is the output you get after running the first command in the usage (train).
And the input you provide in the second command (predict).
