### ISSUE TITLE
Error Loading UBM for training

### ISSUE THREAD

**Issue by ksclark** [ppwwyyxx/speaker-recognition#2]
Hello,

When I try to train the UBM Model I receive the following error

```
the model file:  /var/webapps/speaker-recognition-master/speaker-recognition-master/src/gui/model/ubm.mixture-32.person-20.immature.model

Start training...
training from ubm ...
nr_instance   :   2099
nr_dim        :   28
nr_mixture    :   32
min_covar     :   0.001000
threshold     :   0.010000
nr_iteration  :   200
init_with_kmeans: 0
concurrency   :   1
verbosity     :   0
python2: src/gmm.cc:177: real_t Gaussian::probability_of_fast_exp(std::vector<double>&, double*): Assertion `(int)x.size() == dim' failed.
Aborted (core dumped)
```

Any idea why I get the Assertion fail error

**Comment by ppwwyyxx** [comment]
It looks like the given input feature and the pre-trained ubm model has different dimensions.

Unfortunately I don't remember what feature is used in the pre-trained ubm model. So that model might not be a good point to start with.

**Comment by elmezie** [comment]
Thanks! Do you know how I could create a new ubm model that I can use?

**Comment by ppwwyyxx** [comment]
UBM is simply a GMM trained on a large number of samples.  
src/testbench/train-ubm.py can be used to create an UBM on pre-calculated features.
