### ISSUE TITLE
is the filter very sensitatve to background noise?

### ISSUE THREAD

**Issue by sunnyclaracn** [ppwwyyxx/speaker-recognition#22]
Yuxin, thanks for the great work. I'm using your package and has been worked out the online conversation mode based on you gui version. The only problem I have is the filter seems doesn't work well. 
If I turn off the filter, it runs normally but it can not recognize out when nobody is speaking. It works good though when I keep talking. But If I turn on the filtering, it will filter out all the recorded content and regarded it is nobody even when I keep talking. So I wondering if the filter is too sensitivate to the background noise? 
Or if there is any trick to make it work good?

**Comment by sunnyclaracn** [comment]
What I did now is I will recorde the background noise first, then I will talk. Not matter do the enroll or do the online converstation.

**Comment by ppwwyyxx** [comment]
The filter is meant to filter out the noise and silence, but its parameters may not work well under different noise environment.
Recording the background noise and letting the filter model know about the noise may help sometimes.

**Comment by sunnyclaracn** [comment]
thanks! yes, it works better after tuning the parameter. In addition, I need to record the background noise right before I do the testing each time, right？ Seems not work well if I use previous background noise .

**Comment by ppwwyyxx** [comment]
I'm not sure about that. But if noise is changing over time it'll be better to record noise more often.
