### ISSUE TITLE
Implement speaker-recognition to alexylem/jarvis project

### ISSUE THREAD

**Issue by wikijm** [ppwwyyxx/speaker-recognition#25]
Hi everyone,

I'd like to know if your team could help us to integrate your solution to Jarvis, which is a lightweight configurable multi-lang jarvis-like bot, meant for home automation running on slow computer.

More information here: https://github.com/alexylem/jarvis
Even if the creator is French, the project is most of the time carried in English.

We would like to implement your solution to adapt commands regarding to the requester.
Ex: Read a personal music playlist
=> If John say: "Play some music", Jarvis answer "OK, let's play some rock!"
=> If Jane say: "Play some music", Jarvis answer "OK, let's play some pop."

Thanks in advance.

**Comment by ppwwyyxx** [comment]
Your project seems very interesting.
You can take ideas from this project but unfortunately we're unlikely to devote time to it.

**Comment by wikijm** [comment]
Thanks for your time and your answer.
I hope that we will succeed in implementing your solution without your help.
