### ISSUE TITLE
Unknown speaker recognition with predict_one_with_rejection - Assertion `(int)x.size() == dim' failed

### ISSUE THREAD

**Issue by qacollective** [ppwwyyxx/speaker-recognition#32]
Hi Again,

I am also trying to conduct unknown speaker recognition so I can later add unknown speaker samples to future training data.

It seems that the predict_one_with_rejection method of the GMMSet object is written to help identify unknown speakers?

Unfortunately, when I begin enrollment with the UBM, I receive the following error:

```
Start training...
training from ubm ...
nr_instance   :   18175
nr_dim        :   28
nr_mixture    :   32
min_covar     :   0.001000
threshold     :   0.010000
nr_iteration  :   200
init_with_kmeans: 0
concurrency   :   4
verbosity     :   0
python: src/gmm.cc:177: real_t Gaussian::probability_of_fast_exp(std::vector<double>&, double*): Assertion `(int)x.size() == dim' failed.
python: src/gmm.cc:177: real_t Gaussian::probability_of_fast_exp(std::vector<double>&, double*): Assertion `(int)x.size() == dim' failed.
Aborted (core dumped)
```

However when I enroll without the UBM, everything works fine.

Do you know what this problem is?  Could you explain to me what this assertion is checking?

Is it:
x.size() the number of features
dim the number of dimensions in the GMM
???

**Note** : for me, training without the UBM was the default setting because the path to the UBM in interface.py was incorrect for my system and _get_gmm_set automatically returns a non-ubm GMM set if the model file can't be found.  To fix this, I changed:

`    UBM_MODEL_FILE = 'model/ubm.mixture-32.utt-300.model'`
to
`    UBM_MODEL_FILE = 'gui/model/ubm.mixture-32.utt-300.model'`

Andrew

**Comment by ppwwyyxx** [comment]
We tried ubm but didn't use it in the end. Some of the code is left there but there is no guarantee they still work.
