### ISSUE TITLE
Audio spoofing

### ISSUE THREAD

**Issue by javenosa** [ppwwyyxx/speaker-recognition#33]
Hello,

Nice project.
There is any function or future feature to accomplish audio spoofing (something like detect fake voices) over this project?

Thanks
Javenosa

**Comment by ppwwyyxx** [comment]
Unfortunately there isn't.

**Comment by javenosa** [comment]
Ok, do you any knowledge about this? something to read to develop this function?

Thanks

**Comment by ppwwyyxx** [comment]
The term to google may be "speaker verification"

**Comment by javenosa** [comment]
Yep, I was already look with that term, I mean to develop audio spoofing validation over speaker verification system.
