### ISSUE TITLE
UBM training guidelines

### ISSUE THREAD

**Issue by SarthakYadav** [ppwwyyxx/speaker-recognition#37]
Can you explain to me how to train the UBM on my dataset?
I know we can use testbench/train-ubm.py to train the ubm model.

I want to know:
1. what's the use of adapt-ubm.py?
2. how to setup the directory structure of the data set for training.
3. why does read_raw_data() in src/testbench/datautil.py uses numpy.loadtxt?

**Comment by ppwwyyxx** [comment]
#32
