### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by chananshgong** [ppwwyyxx/speaker-recognition#43]
Do you have installation instruction?
Moreover, how can you enroll before a UBM? Who trains the UBM? was it pre-trained? Or do you assume close-set and use all speaker models to create a UBM?

**Comment by ppwwyyxx** [comment]
The project doesn't need installation.

We tried but didn't use UBM in the end.

**Comment by chananshgong** [comment]
Can you ellaborate on that? do you do ML?

**Comment by ppwwyyxx** [comment]
Elaborate on which?

I do.
