### ISSUE TITLE
I am able to use this program in terminal but not with the GUI

### ISSUE THREAD

**Issue by Abhi001vj** [ppwwyyxx/speaker-recognition#44]
I can't load the 'model.out' that i saved using the speaker-recognition.py into the GUI.I used the GUI like this
I recorded or loaded the file, trained on it, and tried enrolling and then dumbing the trained model so that i can use it again next time.CanI do that train on multiple users and then use that model to make real time predictions using the gui.The enrolling always fails and the training is so fast I have trained on a 2min wav file using the speaker-recognition.py and it was able to recognize the voice on a wav file which was not in the training set but I am not able to do this on GUI>
Thank you.

**Comment by ppwwyyxx** [comment]
The GUI is a quick demo that wasn't maintained for more general use anymore.

**Comment by Abhi001vj** [comment]
Thank you for the reply and this project.
