### ISSUE TITLE
Getting Error 

### ISSUE THREAD

**Issue by ripundeep** [ppwwyyxx/speaker-recognition#49]
Whenever I try to train it with my own voice; it sends me an error and aborted the GUI.

python: src/gmm.cc:177: real_t Gaussian::probability_of_fast_exp(std::vector<double>&, double*): Assertion `(int)x.size() == dim' failed.
python: src/gmm.cc:177: real_t Gaussian::probability_of_fast_exp(std::vector<double>&, double*): Assertion `(int)x.size() == dim' failed.
python: src/gmm.cc:177: real_t Gaussian::probability_of_fast_exp(std::vector<double>&, double*): Assertion `(int)x.size() == dim' failed.
Aborted (core dumped)

Please suggest !!

**Comment by ppwwyyxx** [comment]
There might be some problems with the C++ gmm. You can remove the compiled binary so that it will use sklearn gmm instead.

**Comment by ripundeep** [comment]
Hi, The aforementioned error has been resolved by changing the path of UBM model in interface.py

Please privide me your email address so that I can communicate with you directly in order to successfully execute this project on my machine.  

Regards, 
Ripundeep Gill
