### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by AhmedHanie** [ppwwyyxx/speaker-recognition#5]
Hello, 
Please i am trying to run the GUI to test your program and when i type "\speaker-recognition-master\src\gui>python gui.py"

i get the following: 

`Traceback (most recent call last):
  File "gui.py", line 23, in <module>
    from interface import ModelInterface
  File "C:\Important Documents GP\speaker-recognition-master\src\gui\interface.py", line 16, in <module>
    from feature import mix_feature
ImportError: No module named feature`
  
any help ? 

Thank You

**Comment by ppwwyyxx** [comment]
The project uses several soft links, which are not supported in windows.

**Comment by dalmam11** [comment]
hey thanks for this project!it looks amazing! there is no solution to run it in win os? thanks in advance
