### ISSUE TITLE
Unpredictable results.

### ISSUE THREAD

**Issue by code-player** [ppwwyyxx/speaker-recognition#51]
Over the same dataset I trained on different machines, the misclassified samples are different.
Although few of the all data samples are misclassified over the given dataset, the results varies from machine to machine. Test samples properly identified on one machine are mislabeled on the other.
Do you have any idea about this?

**Comment by ppwwyyxx** [comment]
The algorithms have randomness inherently.

**Comment by code-player** [comment]
So, there's no way the results can be certain ?

**Comment by ppwwyyxx** [comment]
right.

**Comment by blackunicorn47** [comment]
@code-player by mislabeled you mean the results are incorrect & the matching is not showing correct results ?

**Comment by code-player** [comment]
Yeah. Definitely. Over the same dataset (say A-Z) trained over two different machines. One machine misidentifies some users (let say D, M, P) and perfectly identifies the rest, the other machine misidentifies some other users, (like F, O, X) and identifies the rest properly.
This was the issue I asked about.
