### ISSUE TITLE
Unable to install the dependencies

### ISSUE THREAD

**Issue by skulai** [ppwwyyxx/speaker-recognition#57]
Hello,
 I am trying to run the project on Ubuntu. I installed all dependencies by running the dockerfile. It executed successfully. But when I run python speaker_recognition.py , I get this error 

No module named bob
Warning: failed to import Bob, will use a slower version of MFCC instead.
Traceback (most recent call last):
  File "speaker-recognition.py", line 17, in <module>

Could you please tell me if I need to do anything else to make this work?

**Comment by ppwwyyxx** [comment]
https://github.com/ppwwyyxx/speaker-recognition/blob/1d81338169659e9255f823b9bb043b7a1915bc82/Dockerfile#L122

**Comment by skulai** [comment]
>>docker run speaker-recognition
/usr/lib/python2.7/dist-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
usage: speaker-recognition.py [-h] -t TASK -i INPUT -m MODEL
speaker-recognition.py: error: argument -t/--task is required

This is the error I get now after running the above command

**Comment by ppwwyyxx** [comment]
You're already running it. You just need to follow the usage in README

**Comment by skulai** [comment]
@ppwwyyxx  
docker run speaker-recognition -t enroll -i "./shruthi/" -m model.out
/usr/lib/python2.7/dist-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
No valid directory found!

I have a directory with .wav files in the folder src/shruthi. 
Am I doing it correctly?

**Comment by ppwwyyxx** [comment]
`./shruthi` is probably not a valid path in docker.
I'm not familiar with docker, I guess something like `/root/speaker-recognition/src/shruthi` may work.

**Comment by blackunicorn47** [comment]
Hi @skulai , save this txt as a .sh file and run it as administrator. It should work. Do let me know if it worked.


[installer.txt](https://github.com/ppwwyyxx/speaker-recognition/files/1452733/installer.txt)

**Comment by skulai** [comment]
@blackunicorn47 Thank you, I will try this out

**Comment by Fritskee** [comment]
@skulai did it work?

**Comment by qacollective** [comment]
Since people were having trouble building the Dockerfile, I have built a Linux docker image that can be pulled now - simply run `docker pull qacollective/ppwwyyxx-speaker-recognition`
