### ISSUE TITLE
ImportError: No module named scikits.talkbox.linpred

### ISSUE THREAD

**Issue by netttt** [ppwwyyxx/speaker-recognition#58]
when i try to open the python file speaker-recognition.py in the terminal it sends out this error:
ImportError: No module named scikits.talkbox.linpred
how can i fix it?

**Comment by ppwwyyxx** [comment]
Install the dependencies

**Comment by netttt** [comment]
i ran this line:
install blitz, openblas, boost
and it still does the same

**Comment by netttt** [comment]
@ppwwyyxx pls help

**Comment by ppwwyyxx** [comment]
scikits.talkbox is a dependency

**Comment by netttt** [comment]
I managed to download all the dependencies except: scikit-learn and PyQt4
the error was:
Could not find a version that satisfies the requirement scikits-learn (from versions: )
No matching distribution found for scikits-learn

how can i find the version?

**Comment by ppwwyyxx** [comment]
Have you installed scikits.talkbox or not?

**Comment by netttt** [comment]
yes i had

**Comment by ppwwyyxx** [comment]
If the installation is successful you should be able to import.
Could you post the log for the installation of scikits.talkbox?

**Comment by netttt** [comment]
since i have already installed it i can only show you this log, i hope its good enough

Requirement already satisfied: scikits.talkbox in /Users/netanel/Library/Python/2.7/lib/python/site-packages
Requirement already satisfied: numpy in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from scikits.talkbox)

**Comment by ppwwyyxx** [comment]
If the installation appears successful, this can also be a python environment problem, e.g. not using the matching version for pip.

**Comment by netttt** [comment]
so how can i find what is the problem and fix it

**Comment by ppwwyyxx** [comment]
Could you try the command: `python2 -c 'from scikits.talkbox.linpred import levinson_lpc'`.
If it fails, your python cannot find your installed library. I don't know the reason for that and there could be millions of reasons. I suggest find someone around you for help.

This repo also includes a Dockerfile with a full environment to run the program.

**Comment by netttt** [comment]
i tried to run this line
when i had, it simply gave me empty line and then it made the console disable itself, meaning it received my code but it didn't respond to it.

i have also tried to run the speaker-recognition.py file and this time it gave this error:
"no module named sip"
the only dependency i could not achieve was the PyQt4.

**Comment by ppwwyyxx** [comment]
That means you've installed scikits.talkbox successfully and your original problem was __solved__.
Could you please post all the error logs you saw for the new error?

**Comment by netttt** [comment]
when i write: "pip install --user PyQt4",               it gives me this answer:

Collecting PyQt4
  Could not find a version that satisfies the requirement PyQt4 (from versions: )
No matching distribution found for PyQt4

when i try to open the speaker-recognition.py file: "python speaker-recognition.py", the console prints out:

Traceback (most recent call last):
  File "speaker-recognition.py", line 17, in <module>
    from gui.interface import ModelInterface
  File "Desktop/speaker-recognition-master/src/gui/interface.py", line 17, in <module>
    from filters.VAD import VAD
  File "/Desktop/speaker-recognition-master/src/gui/filters/VAD.py", line 9, in <module>
    from ltsd import LTSD_VAD
  File "Desktop/speaker-recognition-master/src/gui/filters/ltsd.py", line 11, in <module>
    import matplotlib.pyplot as plt
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/pyplot.py", line 98, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/backends/__init__.py", line 28, in pylab_setup
    globals(),locals(),[backend_name],0)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/backends/backend_qt4agg.py", line 13, in <module>
    from backend_qt4 import QtCore, QtGui, FigureManagerQT, FigureCanvasQT,\
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/backends/backend_qt4.py", line 25, in <module>
    from qt4_compat import QtCore, QtGui, _getSaveFileName, __version__
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/backends/qt4_compat.py", line 36, in <module>
    import sip
ImportError: No module named sip

**Comment by ppwwyyxx** [comment]
This is unrelated to PyQt4 and is because your matplotlib version is too old.
See https://github.com/ContinuumIO/anaconda-issues/issues/8
