### ISSUE TITLE
Segmentation fault (Core Dumped)

### ISSUE THREAD

**Issue by viju2008** [ppwwyyxx/speaker-recognition#59]
I am trying to use the fast-gmm provided in the src directory

make -C src/gmm
and then ran ./speaker-recognition.py  with required parameters

It labeled the file with the speakers
but after start training

It gave me an error Segmenation fault (core-dumped) 

Can anyone help me resolve this

UBUNTU 14.04 LTS 32 BIT OS

**Comment by gitrohini** [comment]
I have also same problem.

**Comment by ppwwyyxx** [comment]
The C++ gmm was removed from the instructions and will not be used any more.
