### ISSUE TITLE
Segmentation Fault : 11, while running enroll on OSX 

### ISSUE THREAD

**Issue by sanjayshreedharan** [ppwwyyxx/speaker-recognition#6]
Running the following command `python speaker-recognition.py -t enroll -i "./ ./sanjay" -m model.out` gives the following output.

```
Start training...
nr_instance   :   94
nr_dim        :   28
nr_mixture    :   32
min_covar     :   0.001000
threshold     :   0.010000
nr_iteration  :   200
init_with_kmeans: 0
concurrency   :   4
verbosity     :   0
Segmentation fault: 11

```

The program closes saying Segmentation fault : 11. Can you please help me with it?

**Comment by ppwwyyxx** [comment]
The problems seem to be in fast-gmm. @zxytim may have a better idea on what's happening.
Meanwhile, you may choose not to compile the gmm code, then GMM from sklearn will be used instead.

**Comment by sanjayshreedharan** [comment]
I figured that out and used the gmm sklearn. Is there a way to do continuous speaker recognition in command line ? And not GUI?

**Comment by ppwwyyxx** [comment]
Unfortunately there isn't.

**Comment by stanleyguan** [comment]
This doesn't seem to be resolved yet. I ran into the same probelm on macOS. I'm currently falling back to the GMM implementation in sklearn. But it's nice to have the C implementation if that's faster.

**Comment by gitrohini** [comment]
nr_instance   :   1030
nr_dim        :   28
nr_mixture    :   32
min_covar     :   0.001000
threshold     :   0.010000
nr_iteration  :   200
init_with_kmeans: 0
concurrency   :   4
verbosity     :   0
Segmentation fault (core dumped)
I have also same problem ? can anyone help me for resolve it?

**Comment by gitrohini** [comment]
Is there any installation problem ??

**Comment by gitrohini** [comment]
Is there any installation problem ??
