### ISSUE TITLE
problem with predict 

### ISSUE THREAD

**Issue by Sunny-NEU** [ppwwyyxx/speaker-recognition#66]
Hello Yuxin Wu:
    Your project is so cool! And it is successful to train with the voice that i set. However,when i predict a new 
wavfile,  error follows that “R = pickle.load(f)  EOFError”. I doubt that my predict command line is wrong-used.,like "python speaker-recognition.py -t predict -i "trained-file.wav" -m model.out". Where is the fault? Please tell me some of your points.Thanks! Looking forward to your reply!
Note: My Os is win10, and py2.7

**Comment by Sunny-NEU** [comment]
i have fixed the above issue with the operation that "open  with open(fname, 'r') as f" fixed as "open  with open(fname, 'rb') as f". now it has another issue that "No module named interface". Oh My God! What should i do ?

**Comment by Sunny-NEU** [comment]
I have already solved the problem mentioned before. Now i will develop the GUI like that in the video demo next. I hope it will go smoothly.

**Comment by wang1991jun** [comment]
i can't run,segmentation fault(core dumped)

**Comment by wang1991jun** [comment]
can you give me your code?

**Comment by Sunny-NEU** [comment]
@wang1991jun i just fixed the code a little as i said before that "open with open(fname, 'r') as f" was fixed as "open with open(fname, 'rb') as f".What is your issue  exactly? We can exchange idea with each other.

**Comment by Sunny-NEU** [comment]
@ppwwyyxx Are you there? I have pulled out the UI, However, "Upload Photo" can chose a photo but it can't be uploaded to the interface. And when i chose a wavfile to enroll, it reports "Exception: NoiseFilter Not Initialized". I can't find where is wrong.  Many buttons on the UI i pulled out doesn't work.

**Comment by wang1991jun** [comment]
i run in ubantu16.04, but when i run ./speaker-recoginition.py,it product error (Segmentation fault (Core Dumped)).do you have this error? you use which system?
this is my qq:850722750,In order to facilitate communication, can you add me as a friend?

**Comment by wang1991jun** [comment]
I think my problem may be caused by Gcc, I do not know which version you are using?

**Comment by Sunny-NEU** [comment]
@wang1991jun My OS is Win10 and run code on Windows system, not  ubantu.....

**Comment by ppwwyyxx** [comment]
As said in the README, the GUI part is for demo purposes and not maintained anymore. The command line tool is expected to work and should not produce segmentation fault after recent changes to the installation instructions. 
If you meet any issues, please report a full bug report.
