### ISSUE TITLE
Docker build fails with no module named sp

### ISSUE THREAD

**Issue by ChillarAnand** [ppwwyyxx/speaker-recognition#68]
`docker build .` fails with this error

```
Collecting bob.ap (from bob.bio.spear)
  Downloading bob.ap-2.1.5.zip (87kB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-ZZTsV0/bob.ap/setup.py", line 42, in <module>
        bob_packages = bob_packages,
      File "/usr/local/lib/python2.7/dist-packages/bob/blitz/extension.py", line 52, in __init__
        BobExtension.__init__(self, *args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/bob/extension/__init__.py", line 301, in __init__
        bob_includes, bob_libraries, bob_library_dirs, bob_macros = get_bob_libraries(self.bob_packages)
      File "/usr/local/lib/python2.7/dist-packages/bob/extension/__init__.py", line 193, in get_bob_libraries
        pkg = importlib.import_module(package)
      File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
        __import__(name)
    ImportError: No module named sp
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-ZZTsV0/bob.ap/
The command '/bin/sh -c pip2 install bob.bio.spear' returned a non-zero code: 1
```

**Comment by andreaschandra** [comment]
make sure you install bob correctly

**Comment by qacollective** [comment]
Hi,

Sorry when I authored the Dockerfile, the first line was just `FROM ubuntu` which worked for me at the time I was building it, but that will always retrieve the latest ubuntu version.  Now that time has moved on, the ubuntu image and package repositories have changed which may have been a source of difficulty.

I've just successfully built the Docker image again on ubuntu 16.04 so I'll submit a pull request to make those changes.

From then, the only other source of potential error is that the repositories (either ubuntu or python) change and no longer play nice together.  This is why Docker has the Docker Hub so we can share working images.  Accordingly, I've uploaded my working image.  So now you can get a working version of this project from the command line by simply typing `docker pull qacollective/ppwwyyxx-speaker-recognition`

**Comment by qacollective** [comment]
This issue can be closed.
