### ISSUE TITLE
cannot run noisered.py

### ISSUE THREAD

**Issue by Victorl2000** [ppwwyyxx/speaker-recognition#7]
Hi ,
i am new with python. I tried to run filters/noisered.py in command line, but got error:
  File "<stdin>", line 1, in <module>
  File "utils.py", line 1
    ../gui/utils.py
    ^
SyntaxError: invalid syntax

I think I can use sys.path.insert(0, "../gui/") to resolve this problem. But i wonder why the original way of setting dos not work. 
In this directory, the file utils.py just have one line: ../gui/utils.py, how does this work?
I am using python 2.7.6

Thanks,
Vic

**Comment by ppwwyyxx** [comment]
utils.py is a symlink. But you're using windows which doesn't support symlink.

**Comment by Victorl2000** [comment]
i am running on Linux box.

**Comment by ppwwyyxx** [comment]
Then either you have copied the files to/from windows, or you're putting the files on a file system which doesn't support symlink, e.g. NTFS which is used by windows.

**Comment by Victorl2000** [comment]
many thanks!
