### ISSUE TITLE
scikits.talkbox install failed

### ISSUE THREAD

**Issue by dalmam11** [ppwwyyxx/speaker-recognition#70]
I installed scikits.talkbox on python 2 and it's installed normally .The problem that i have to use python 3 because tensorflow is compatible only with python 3 on windows .Here some comments on the command prompt when i try to install scikits.talkbox .
For example:
*Running setup.py bdist_wheel for scikits.talkbox ... error
*No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
*LINK : error LNK2001: unresolved external symbol PyInit__lpc
*build\temp.win-amd64-3.6\Release\scikits\talkbox\linpred\src_lpc.cp36-win_amd64.lib : fatal error LNK1120: 1 unresolved externals
*\scikits\talkbox\linpred_lpc.cp36-win_amd64.pyd /IMPLIB:build\temp.win-amd64-3.6\Release\scikits\talkbox\linpred\src_lpc.cp36-win_amd64.lib" failed with exit status 1120
*Failed building wheel for scikits.talkbox
*failed with error code 1 in C:\Users\DALIKA~1\AppData\Local\Temp\pip-build-sq6cbxni\scikits.talkbox
how can i resolve this problems please . Kinds regards

**Comment by ppwwyyxx** [comment]
Please report the issue to `scikits.talkbox` if you have trouble installing it.

**Comment by andreaschandra** [comment]
worked well on python 2

**Comment by ppwwyyxx** [comment]
This is a question about scikits.talkbox and not directly related to this project. Closing now and you can ask scikit community for help.
