### ISSUE TITLE
How to Train UBM Model?

### ISSUE THREAD

**Issue by chrisspen** [ppwwyyxx/speaker-recognition#71]
I was able to train the system to very accurately recognize known speakers. The default command line interface doesn't seem to handle unknown speakers. Looking through the code, I see UBM.py, which seems to be the basis for identifying unknown speakers, by matching them with a universal model, generalized from the other speakers. However, I can't find any example of how to train the UBM, and this file doesn't appear to be referenced anywhere else in the code. Was this UBM functionality finished, or is it incomplete? How do you train it from your sample files?

**Comment by andreaschandra** [comment]
any update on this?

**Comment by chrisspen** [comment]
Yeah, I implemented a rudimentary solution. See my fork [here](https://github.com/chrisspen/speaker-recognition-1/blob/master/src/speaker-recognition.py). The general strategy is dual-train every sample with a "universal" label to create the UBM. Then, when you classify a sample, if the UBM label is given as the most likely class, that means the classifier doesn't recognize it.
