### ISSUE TITLE
Segmentation fault (core dumped) and creating core.13071 file instent of model.out

### ISSUE THREAD

**Issue by gitrohini** [ppwwyyxx/speaker-recognition#76]
[root@aio src]# ./speaker-recognition.py -t enroll -i "./train4/" -m model3.out
Label train4 has files ./train4/tone-8Khz.wav
/root/anaconda2/lib/python2.7/site-packages/scipy/fftpack/basic.py:160: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  z[index] = x
m: <gui.interface.ModelInterface object at 0x7ff30d726050>
output_model: model3.out
Now speaker-recognition.py/before m.train()
Start training...

nr_instance   :   499
nr_dim        :   28
nr_mixture    :   32
min_covar     :   0.001000
threshold     :   0.010000
nr_iteration  :   200
init_with_kmeans: 0
concurrency   :   4
verbosity     :   0
Segmentation fault (core dumped)
I found that fault is in gmm/src/pygmm.cc file in train_model()? why and how to remove it Any suggestion....  and please give me sample input file set and what should be output for that ??

**Comment by ppwwyyxx** [comment]
Now the C++ implementation of GMM will not be used and segfault should not happen again.
