### ISSUE TITLE
Add requirements.txt

### ISSUE THREAD

**Issue by NavneetNandan** [ppwwyyxx/speaker-recognition#77]
Kindly add a requirements.txt file having all dependencies.

**Comment by ppwwyyxx** [comment]
Adding it will not help much because many python dependencies of this project have their own C library dependencies, which means that `pip install -r requirements.txt` will fail on an empty system.

You can refer to the docker file on how to install dependencies.

**Comment by Aurora11111** [comment]
@ppwwyyxx Is it means that this project must run on docker?

**Comment by ppwwyyxx** [comment]
It does not

**Comment by Aurora11111** [comment]
@ppwwyyxx how to excute  your command when in archlinux?
