### ISSUE TITLE
where is the script mix_feature in feature?

### ISSUE THREAD

**Issue by v-yunbin** [ppwwyyxx/speaker-recognition#79]
where is the script mix_feature in feature?
from feature import mix_feature in 'interface.py'
i can not find the script.

**Comment by ppwwyyxx** [comment]
https://github.com/ppwwyyxx/speaker-recognition/blob/master/src/feature/__init__.py#L25

**Comment by v-yunbin** [comment]
@ppwwyyxx thanks
