### ISSUE TITLE
work flow and other questions

### ISSUE THREAD

**Issue by Victorl2000** [ppwwyyxx/speaker-recognition#8]
Your package is  really a good one. But I have a lot of question on using it. I just started reading, and  
1.  is it free to use your package? Should i put any citation?
2. you reported MFCC and LPC performance, they are separate experiments, not combined, right? is there any comparison between MFCC and LPC?
3. There are several methods for removing noise, which one is the best? For VAD one, it just remove noise, but for the noisered one, you also do some noise cancellation?
4. what is the sampling frequency of the speech data for the wav? 16KHz by default? did not see this in your doc.
5. in Final-report: Page 10 under 3. Implementation, it said: we have found that the following parameters are optimal" and "number of cepstral coefficient is 15", but in Page16, under 5.5, it stated that 19 cepstrums MFCC is the best. Please clarify and confirm.
6. can you give me a work flow of the processes? especially i want to use it piece by piece, not in the gui, for example:  
the speech files from a few speakers --> remove_noise, ---> ubm
                                                                                         --->gmms
i am new to python, hope have more detail info, like the parameters for running your tools.

Thanks
Vic

**Comment by ppwwyyxx** [comment]
1. It's free and you could simply cite the github repo.
2. Right. We didn't have the comparison between them but I'm sure MFCC would be better.
3. `VAD` uses LTSD algorithm and `NoiseRedction` uses the sox software. Technically they did different things, one to detect voice activity, one to remove noise, but the effects are similar. VAD might be a bit better but it may depend on the data.
4. We only use 8khz signals.
5. 19 just happened to be what we used for that specific experiment, not necessarily a best one. And from what I remembered, the two MFCC implementation (one from BOB and one written in code) has different optimal values but I can't remember much about it.
6. UBM was not found very useful for recognition. There is a command line tools `speaker-recognition.py` that contains the "training-predicting" workflow, without noise reduction or VAD.

**Comment by Victorl2000** [comment]
Thanks for answering my lots of Qs. 
Please confirm if i understand correctly: 
      - Your final demo only uses GMMs for the recognition (predicting),  each speaker has a GMM with 32 mix
      - JFA, NN and  UBM are NOT used in the demo (because they do not help much in the performance)

I remember you mentioned using MFCC+DeltaMFCC. I have concerns about using DeltaMFCC part: after you remove silence/noise, the Delta part may introduce more variation. Have you compared using MFCC alone with MFCC+DeltaMFCC?

**Comment by Victorl2000** [comment]
Hi,
In the demo, what knid of models are used for GMMs and UBM?
Thanks,
Vic

**Comment by ppwwyyxx** [comment]
Yes only GMM with 32 mix is used in the demo. I don't remember any tests about deltamfcc and noise removal.

**Comment by Victorl2000** [comment]
Great! From what i learned from the code, ubm.mixture-32.utt-300.model are used. I think this UBM is a GMM with 32-mix. Also, each enrolled speaker has a GMM. So at the the predict stage, all the models are GMMs with 32-mix (w/ or w/o UBM). Using UBM is only for prediting with rejection. If there is no rejection, then UBM is actually not used, only the enrolled speaker's GMMs are used. Pls confirm if this is right.

**Comment by ppwwyyxx** [comment]
Yes this sounds right.

**Comment by Victorl2000** [comment]
Thanks Yuxin.
In the demo, how much data is needed for each enrolled speaker for better performance? 
Do you train the GMM for each speaker or adapt the UBM models to create the speaker's GMM?

**Comment by ppwwyyxx** [comment]
Several minutes (5?) I think.
The models are trained from scratch.
