### ISSUE TITLE
what's the problem? 

### ISSUE THREAD

**Issue by savesociety** [ppwwyyxx/speaker-recognition#81]
I've two problems
in training, segmentation fault(core dump)
in predicting, no such file or directory : 'model.out'
![screenshot from 2018-12-07 10-00-02](https://user-images.githubusercontent.com/37554692/49632568-383c6f80-fa07-11e8-81a4-574a3138eed0.png)

**Comment by ppwwyyxx** [comment]
I've removed the instructions about the C++ GMM implementation. Training will not segfault if you do not compile the C++ GMM, then the code will use sklearn.

Predict says no such file or directory, because training is supposed to output a model if it succeeded.

**Comment by savesociety** [comment]
Thank you so much. It works. 
![screenshot from 2018-12-07 10-45-41](https://user-images.githubusercontent.com/37554692/49634296-560cd300-fa0d-11e8-9d95-f4dac0848efa.png)

**Comment by ppwwyyxx** [comment]
That's great to hear!
Closing.
