### ISSUE TITLE
GUI - Version calculation of score

### ISSUE THREAD

**Issue by SFeli** [ppwwyyxx/speaker-recognition#9]
Hi,
thx for the great work. I have learned a lot and the speaker-recognition on command line works fine. The gui has in my environment linux python2.7 a problem. The calculation of scores is not working.
Is there a option to check if the "learned models" are available and consistent?
On my investigation I have found one little mistake in gui.py in def updateUserInfo there the line
349 u = self.serdata[userindex] should be updated to 
       u = self.userdata[userindex]
Regards from Germany

**Comment by ppwwyyxx** [comment]
Thanks. The GUI is more or less a simple and dirty demo. I myself didn't fully remember the correct steps to make it work smoothly. But since you can load model by manually clicking the `load` button, I assume it should work fine.
